### ISSUE TITLE
metric problem

### ISSUE THREAD

**Issue by nicehuster** [callsys/ControlCap#5]
the test dataset for evaluating VG benchmark have some problem, in original GRiT test set [https://datarelease.blob.core.windows.net/grit/VG_preprocessed_annotations/test.json](url) , each image has multiple regions for caption generation and evaluation,   in your test data only have one region, what's problem?

**Comment by callsys** [comment]
For dense captioning, we use the same test set with GRiT(`vg/test.json`, each image has multiple regions). For referring expression generation, we use the same test set with GlaMM(`vg_reg/test.json`, each image has single region).

**Comment by nicehuster** [comment]
It seems that GlaMM is incorrect. I have checked both the test sets used in [ASM](https://arxiv.org/abs/2308.01907) and [TAP](https://arxiv.org/abs/2312.09128) , when calculating CIDEr and METEOR, each image in the test set contains multiple regions instead of just one.

**Comment by callsys** [comment]
When testing the captioning performance on VG, some algorithm's test set contains one region (GlaMM, Groma), while the others contain multiple regions (ASM, TAP), the comparison of these methods is certain unfair. Since many algorithms follow GlaMM's approach (Alpha-CLIP, Osprey), we decided to use GlaMM's test set. In our experiment, testing on ASM test set was slightly lower than on GlaMM (meteor was about 1 lower).

**Comment by nicehuster** [comment]
Thanks for your reply.  I evaluated the official GRiT, and the metric is (CIDEr: 145.0, METEOR:17.3).  the related codes are avaliable in this repo[GRiT-eval](https://github.com/nicehuster/GRiT-eval).

**Comment by callsys** [comment]
Thank you for your discussion, we will test the referring expression performance on the full set of VG so the proposed approach can be compared with ASM and TAP.
